[test]
levels = ["install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = ["depth_normal"]
gpu = ["recon"]

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
