[cuda]
packages = ["gsplat", "flash-attn"]

[dependencies]
av = "*"
numpy = ">=1.24.0"
pillow = ">=10.0.0"
scipy = ">=1.11.0"
matplotlib = ">=3.9.0"
psutil = ">=5.9.0"
trimesh = "*"
plyfile = ">=1.0.0"
opencv = ">=4.9.0"
huggingface_hub = "*"
tqdm = "*"

[target.linux-64.dependencies]
c-compiler = "*"

[target.win-64.pypi-dependencies]
triton-windows = ">=3.5.0"

[pypi-dependencies]
safetensors = ">=0.4.0,<1.0.0"
omegaconf = ">=2.3.0,<3.0.0"
einops = ">=0.7.0,<1.0.0"
pycolmap = "*"
onnxruntime = "*"
moviepy = "==1.0.3"
pillow_heif = "*"
torchmetrics = "*"
colorspacious = "*"
jaxtyping = "*"
typeguard = "*"
pydantic = "*"
uniception = "*"